---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: golang-1.11
- name: golang-1.12
- name: golang-release
- name: stemcell

outputs:
- name: golang-release
  path: bumped-golang-release

run:
  path: golang-release/ci/tasks/bump.sh

params:
  PRIVATE_YAML: ~
